version: '3.7'
services:
  server:
    container_name: litten-server
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '8080:8080'
    networks:
      - litten-network
    depends_on:
      - mongo

  mongo:
    container_name: litten-mongo
    image: mongo:4.2
    volumes:     
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - litten-network

networks:
  litten-network:
    driver: bridge

volumes:
  mongo_data:
  node_modules:  
